<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convertActiveSessionsListtoExcelBytes</value>
  <array name="sig" type="value" depth="1">
    <value>[i] record:1:optional list</value>
    <value>[i] - field:0:optional nik</value>
    <value>[i] - field:0:optional name</value>
    <value>[i] - field:0:optional email</value>
    <value>[i] - field:0:optional mobileNo</value>
    <value>[i] - field:0:optional processStage</value>
    <value>[i] - field:0:optional processStartTime</value>
    <value>[i] - field:0:optional processLastUpdatedTime</value>
    <value>[o] object:0:optional byteArray</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCkhTU0ZXb3JrYm9vayB3b3JrYm9vayA9IG5ldyBIU1NGV29ya2Jvb2soKTsKSFNTRlNo
ZWV0IHNoZWV0ID0gd29ya2Jvb2suY3JlYXRlU2hlZXQoIk9ubGluZU9uYm9hcmRpbmciKTsKCkZv
bnQgaGVhZGVyRm9udCA9IHdvcmtib29rLmNyZWF0ZUZvbnQoKTsKaGVhZGVyRm9udC5zZXRGb250
SGVpZ2h0SW5Qb2ludHMoKHNob3J0KSAxMyk7CmhlYWRlckZvbnQuc2V0Q29sb3IoSW5kZXhlZENv
bG9ycy5CUk9XTi5nZXRJbmRleCgpKTsKClN0cmluZ1tdIGNvbHVtbnMgPSB7IlByb2Nlc3MgU3Rh
cnQgVGltZSIsIk5JSyIsICJOYW1lIiwgIlByb2Nlc3MgTGFzdCBVcGRhdGVkIiwgIkVtYWlsIiwi
TW9iaWxlIE51bWJlciIsIlByb2Nlc3MgU3RhZ2UifTsKCkNlbGxTdHlsZSBoZWFkZXJDZWxsU3R5
bGUgPSB3b3JrYm9vay5jcmVhdGVDZWxsU3R5bGUoKTsKaGVhZGVyQ2VsbFN0eWxlLnNldEZvbnQo
aGVhZGVyRm9udCk7CgpSb3cgaGVhZGVyUm93ID0gc2hlZXQuY3JlYXRlUm93KDApOwoKLy8gQ3Jl
YXRlIGNlbGxzCmZvcihpbnQgaSA9IDA7IGkgPCBjb2x1bW5zLmxlbmd0aDsgaSsrKSB7CiAgICBD
ZWxsIGNlbGwgPSBoZWFkZXJSb3cuY3JlYXRlQ2VsbChpKTsKICAgIGNlbGwuc2V0Q2VsbFZhbHVl
KGNvbHVtbnNbaV0pOwogICAgY2VsbC5zZXRDZWxsU3R5bGUoaGVhZGVyQ2VsbFN0eWxlKTsKfQoK
aW50IHJvd051bSA9IDE7CklEYXRhW10JbGlzdCA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KCBw
aXBlbGluZUN1cnNvciwgImxpc3QiICk7CmlmICggbGlzdCAhPSBudWxsKQp7Cglmb3IgKCBpbnQg
aSA9IDA7IGkgPCBsaXN0Lmxlbmd0aDsgaSsrICkKCXsKCQlJRGF0YUN1cnNvciBsaXN0Q3Vyc29y
ID0gbGlzdFtpXS5nZXRDdXJzb3IoKTsKCQkJU3RyaW5nCW5payA9IElEYXRhVXRpbC5nZXRTdHJp
bmcoIGxpc3RDdXJzb3IsICJuaWsiICk7CgkJCVN0cmluZwluYW1lID0gSURhdGFVdGlsLmdldFN0
cmluZyggbGlzdEN1cnNvciwgIm5hbWUiICk7CgkJCVN0cmluZwllbWFpbCA9IElEYXRhVXRpbC5n
ZXRTdHJpbmcoIGxpc3RDdXJzb3IsICJlbWFpbCIgKTsKCQkJU3RyaW5nCW1vYmlsZU5vID0gSURh
dGFVdGlsLmdldFN0cmluZyggbGlzdEN1cnNvciwgIm1vYmlsZU5vIiApOwoJCQlTdHJpbmcJcHJv
Y2Vzc0xhc3RVcGRhdGVkVGltZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIGxpc3RDdXJzb3IsICJw
cm9jZXNzTGFzdFVwZGF0ZWRUaW1lIiApOwoJCQlTdHJpbmcJcHJvY2Vzc1N0YXJ0VGltZSA9IElE
YXRhVXRpbC5nZXRTdHJpbmcoIGxpc3RDdXJzb3IsICJwcm9jZXNzU3RhcnRUaW1lIiApOwoJCQlT
dHJpbmcJcHJvY2Vzc1N0YWdlID0gSURhdGFVdGlsLmdldFN0cmluZyggbGlzdEN1cnNvciwgInBy
b2Nlc3NTdGFnZSIgKTsKCQkJCgkJCVJvdyByb3cgPSBzaGVldC5jcmVhdGVSb3cocm93TnVtKysp
OwoJCQlyb3cuY3JlYXRlQ2VsbCgwKS5zZXRDZWxsVmFsdWUocHJvY2Vzc1N0YXJ0VGltZSk7CgkJ
CXJvdy5jcmVhdGVDZWxsKDEpLnNldENlbGxWYWx1ZShuaWspOwoJCQlyb3cuY3JlYXRlQ2VsbCgy
KS5zZXRDZWxsVmFsdWUobmFtZSk7CgkJCXJvdy5jcmVhdGVDZWxsKDMpLnNldENlbGxWYWx1ZShw
cm9jZXNzTGFzdFVwZGF0ZWRUaW1lKTsKCQkJcm93LmNyZWF0ZUNlbGwoNCkuc2V0Q2VsbFZhbHVl
KGVtYWlsKTsKCQkJcm93LmNyZWF0ZUNlbGwoNSkuc2V0Q2VsbFZhbHVlKG1vYmlsZU5vKTsKCQkJ
cm93LmNyZWF0ZUNlbGwoNikuc2V0Q2VsbFZhbHVlKHByb2Nlc3NTdGFnZSk7CgkJCQoJCQkKCQkJ
CgkJbGlzdEN1cnNvci5kZXN0cm95KCk7Cgl9Cn0gCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsK
c2hlZXQuYXV0b1NpemVDb2x1bW4oMCk7ICAgIApzaGVldC5hdXRvU2l6ZUNvbHVtbigxKTsKc2hl
ZXQuYXV0b1NpemVDb2x1bW4oMik7CnNoZWV0LmF1dG9TaXplQ29sdW1uKDMpOwpzaGVldC5hdXRv
U2l6ZUNvbHVtbig0KTsKc2hlZXQuYXV0b1NpemVDb2x1bW4oNSk7CnNoZWV0LmF1dG9TaXplQ29s
dW1uKDYpOwoKQnl0ZUFycmF5T3V0cHV0U3RyZWFtIGJvcyA9IG5ldyBCeXRlQXJyYXlPdXRwdXRT
dHJlYW0oKTsKdHJ5IHsKICAgIHRyeSB7CgkJd29ya2Jvb2sud3JpdGUoYm9zKTsKCQlib3MuY2xv
c2UoKTsKCX0gY2F0Y2ggKElPRXhjZXB0aW9uIGUpIHsKCQkvLyBUT0RPIEF1dG8tZ2VuZXJhdGVk
IGNhdGNoIGJsb2NrCgkJZS5wcmludFN0YWNrVHJhY2UoKTsKCX0KfSBmaW5hbGx5IHsKICAgIHRy
eSB7CgkJYm9zLmNsb3NlKCk7Cgl9IGNhdGNoIChJT0V4Y2VwdGlvbiBlKSB7CgkJLy8gVE9ETyBB
dXRvLWdlbmVyYXRlZCBjYXRjaCBibG9jawoJCWUucHJpbnRTdGFja1RyYWNlKCk7Cgl9Cn0KLy8g
cGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9IHBpcGVsaW5lLmdldEN1cnNv
cigpOwpieXRlW10gYnl0ZUFycmF5ID0gYm9zLnRvQnl0ZUFycmF5KCk7CklEYXRhVXRpbC5wdXQo
IHBpcGVsaW5lQ3Vyc29yXzEsICJieXRlQXJyYXkiLCBieXRlQXJyYXkgKTsKcGlwZWxpbmVDdXJz
b3JfMS5kZXN0cm95KCk7CgkKCQoJCgkKCQoJCgkKCQoJCg==</value>
</Values>
