<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">convertDocumentListtoExcelBytes</value>
  <array name="sig" type="value" depth="1">
    <value>[i] record:1:optional list</value>
    <value>[i] - field:0:optional nik</value>
    <value>[i] - field:0:optional cifNo</value>
    <value>[i] - field:0:optional accountNo</value>
    <value>[i] - field:0:optional cardNo</value>
    <value>[i] - field:0:optional cardExpiry</value>
    <value>[i] - field:0:optional createCIFStatus</value>
    <value>[i] - field:0:optional updateCIFStatus</value>
    <value>[i] - field:0:optional errorDetails</value>
    <value>[i] - field:0:optional cifProcessTime</value>
    <value>[i] - field:0:optional processStartTime</value>
    <value>[i] - field:0:optional source</value>
    <value>[i] - field:0:required marketingCode</value>
    <value>[i] - field:0:required securitiesCompany</value>
    <value>[i] - field:0:required referralCode</value>
    <value>[i] - field:0:required saving</value>
    <value>[i] - field:0:required ebs</value>
    <value>[i] - field:0:required cc</value>
    <value>[i] - field:0:required ics</value>
    <value>[i] - field:0:required inputForm</value>
    <value>[i] - field:0:required mobileOTP</value>
    <value>[i] - field:0:required mobileMPIN</value>
    <value>[o] object:0:optional byteArray</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUgCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7CgpIU1NGV29ya2Jvb2sgd29ya2Jvb2sgPSBuZXcgSFNTRldvcmtib29rKCk7CkhTU0ZT
aGVldCBzaGVldCA9IHdvcmtib29rLmNyZWF0ZVNoZWV0KCJPbmxpbmVPbmJvYXJkaW5nIik7CgpG
b250IGhlYWRlckZvbnQgPSB3b3JrYm9vay5jcmVhdGVGb250KCk7CmhlYWRlckZvbnQuc2V0Rm9u
dEhlaWdodEluUG9pbnRzKChzaG9ydCkgMTMpOwpoZWFkZXJGb250LnNldENvbG9yKEluZGV4ZWRD
b2xvcnMuQlJPV04uZ2V0SW5kZXgoKSk7CgpTdHJpbmdbXSBjb2x1bW5zID0geyJOSUsiLCAiQ0lG
IENyZWF0aW9uIFN0YXR1cyIsICJDSUYiLCJBY2NvdW50IE51bWJlciIsICJDYXJkIE51bWJlciIs
ICJDYXJkIEV4cGlyeSIsICJVcGRhdGUgQ0lGIFByb2ZpbGUgU3RhdHVzIiwiQ0lGIFByb2Nlc3Mg
TGFzdCBVcGRhdGVkIiwiUHJvY2VzcyBTdGFydCBUaW1lIiwiU291cmNlIiwiTWFya2V0aW5nIENv
ZGUiLCJSZWZlcnJhbCBDb2RlIiwiRXJyb3IgRGV0YWlscyIsIlNlY3VyaXRpZXMgQ29tcGFueSIs
IlNhdmluZyIsIkhQIEVCUyIsIkNyZWRpdCBDYXJkIiwiSFAgSUNTIiwiSW5wdXQgRm9ybSIsIk1v
YmlsZSBPVFAiLCJNb2JpbGUgTVBJTiJ9OwoKQ2VsbFN0eWxlIGhlYWRlckNlbGxTdHlsZSA9IHdv
cmtib29rLmNyZWF0ZUNlbGxTdHlsZSgpOwpoZWFkZXJDZWxsU3R5bGUuc2V0Rm9udChoZWFkZXJG
b250KTsKClJvdyBoZWFkZXJSb3cgPSBzaGVldC5jcmVhdGVSb3coMCk7CgoKLy8gQ3JlYXRlIGNl
bGxzCmZvcihpbnQgaSA9IDA7IGkgPCBjb2x1bW5zLmxlbmd0aDsgaSsrKSB7CiAgICBDZWxsIGNl
bGwgPSBoZWFkZXJSb3cuY3JlYXRlQ2VsbChpKTsKICAgIGNlbGwuc2V0Q2VsbFZhbHVlKGNvbHVt
bnNbaV0pOwogICAgY2VsbC5zZXRDZWxsU3R5bGUoaGVhZGVyQ2VsbFN0eWxlKTsKfQoKaW50IHJv
d051bSA9IDE7CklEYXRhW10JbGlzdCA9IElEYXRhVXRpbC5nZXRJRGF0YUFycmF5KCBwaXBlbGlu
ZUN1cnNvciwgImxpc3QiICk7CmlmICggbGlzdCAhPSBudWxsKQp7Cglmb3IgKCBpbnQgaSA9IDA7
IGkgPCBsaXN0Lmxlbmd0aDsgaSsrICkKCXsKCQlJRGF0YUN1cnNvciBsaXN0Q3Vyc29yID0gbGlz
dFtpXS5nZXRDdXJzb3IoKTsgCgkJCVN0cmluZwluaWsgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBs
aXN0Q3Vyc29yLCAibmlrIiApOwoJCQlTdHJpbmcJY2lmTm8gPSBJRGF0YVV0aWwuZ2V0U3RyaW5n
KCBsaXN0Q3Vyc29yLCAiY2lmTm8iICk7CgkJCVN0cmluZwlhY2NvdW50Tm8gPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKCBsaXN0Q3Vyc29yLCAiYWNjb3VudE5vIiApOwoJCQlTdHJpbmcJY2FyZE5vID0g
SURhdGFVdGlsLmdldFN0cmluZyggbGlzdEN1cnNvciwgImNhcmRObyIgKTsKCQkJU3RyaW5nCWNh
cmRFeHBpcnkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBsaXN0Q3Vyc29yLCAiY2FyZEV4cGlyeSIg
KTsKCQkJU3RyaW5nCWNyZWF0ZUNJRlN0YXR1cyA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIGxpc3RD
dXJzb3IsICJjcmVhdGVDSUZTdGF0dXMiICk7CgkJCVN0cmluZwl1cGRhdGVDSUZTdGF0dXMgPSBJ
RGF0YVV0aWwuZ2V0U3RyaW5nKCBsaXN0Q3Vyc29yLCAidXBkYXRlQ0lGU3RhdHVzIiApOwoJCQlT
dHJpbmcJZXJyb3JEZXRhaWxzID0gSURhdGFVdGlsLmdldFN0cmluZyggbGlzdEN1cnNvciwgImVy
cm9yRGV0YWlscyIgKTsKCQkJU3RyaW5nCWNpZlByb2Nlc3NUaW1lID0gSURhdGFVdGlsLmdldFN0
cmluZyggbGlzdEN1cnNvciwgImNpZlByb2Nlc3NUaW1lIiApOwoJCQlTdHJpbmcJcHJvY2Vzc1N0
YXJ0VGltZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIGxpc3RDdXJzb3IsICJwcm9jZXNzU3RhcnRU
aW1lIiApOwoJCQlTdHJpbmcJc291cmNlID0gSURhdGFVdGlsLmdldFN0cmluZyggbGlzdEN1cnNv
ciwgInNvdXJjZSIgKTsKCQkJU3RyaW5nICBtYXJrZXRpbmdDb2RlID0gSURhdGFVdGlsLmdldFN0
cmluZyggbGlzdEN1cnNvciwgIm1hcmtldGluZ0NvZGUiKTsKCQkJU3RyaW5nICBzZWN1cml0aWVz
Q29tcGFueSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIGxpc3RDdXJzb3IsICJzZWN1cml0aWVzQ29t
cGFueSIpOwoJCQlTdHJpbmcgIHJlZmVycmFsQ29kZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIGxp
c3RDdXJzb3IsICJyZWZlcnJhbENvZGUiKTsKCQkJU3RyaW5nICBzYXZpbmcgPSBJRGF0YVV0aWwu
Z2V0U3RyaW5nKCBsaXN0Q3Vyc29yLCAic2F2aW5nIik7CgkJCVN0cmluZyAgZWJzID0gSURhdGFV
dGlsLmdldFN0cmluZyggbGlzdEN1cnNvciwgImVicyIpOwoJCQlTdHJpbmcgIGNjID0gSURhdGFV
dGlsLmdldFN0cmluZyggbGlzdEN1cnNvciwgImNjIik7CgkJCVN0cmluZyAgaWNzID0gSURhdGFV
dGlsLmdldFN0cmluZyggbGlzdEN1cnNvciwgImljcyIpOwoJCQlTdHJpbmcgIGlucHV0Rm9ybSA9
IElEYXRhVXRpbC5nZXRTdHJpbmcoIGxpc3RDdXJzb3IsICJpbnB1dEZvcm0iKTsKCQkJU3RyaW5n
ICBtb2JpbGVPVFAgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBsaXN0Q3Vyc29yLCAibW9iaWxlT1RQ
Iik7CgkJCVN0cmluZyAgbW9iaWxlTVBJTiA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIGxpc3RDdXJz
b3IsICJtb2JpbGVNUElOIik7CgkJCQoJCQlSb3cgcm93ID0gc2hlZXQuY3JlYXRlUm93KHJvd051
bSsrKTsKCQkJcm93LmNyZWF0ZUNlbGwoMCkuc2V0Q2VsbFZhbHVlKG5payk7CgkJCXJvdy5jcmVh
dGVDZWxsKDEpLnNldENlbGxWYWx1ZShjcmVhdGVDSUZTdGF0dXMpOwoJCQlyb3cuY3JlYXRlQ2Vs
bCgyKS5zZXRDZWxsVmFsdWUoY2lmTm8pOwoJCQlyb3cuY3JlYXRlQ2VsbCgzKS5zZXRDZWxsVmFs
dWUoYWNjb3VudE5vKTsKCQkJcm93LmNyZWF0ZUNlbGwoNCkuc2V0Q2VsbFZhbHVlKGNhcmRObyk7
CgkJCXJvdy5jcmVhdGVDZWxsKDUpLnNldENlbGxWYWx1ZShjYXJkRXhwaXJ5KTsKCQkJcm93LmNy
ZWF0ZUNlbGwoNikuc2V0Q2VsbFZhbHVlKHVwZGF0ZUNJRlN0YXR1cyk7CgkJCXJvdy5jcmVhdGVD
ZWxsKDcpLnNldENlbGxWYWx1ZShjaWZQcm9jZXNzVGltZSk7CgkJCXJvdy5jcmVhdGVDZWxsKDgp
LnNldENlbGxWYWx1ZShwcm9jZXNzU3RhcnRUaW1lKTsKCQkJcm93LmNyZWF0ZUNlbGwoOSkuc2V0
Q2VsbFZhbHVlKHNvdXJjZSk7CgkJCXJvdy5jcmVhdGVDZWxsKDEwKS5zZXRDZWxsVmFsdWUobWFy
a2V0aW5nQ29kZSk7CgkJCXJvdy5jcmVhdGVDZWxsKDExKS5zZXRDZWxsVmFsdWUocmVmZXJyYWxD
b2RlKTsJCQkJCQoJCQlyb3cuY3JlYXRlQ2VsbCgxMikuc2V0Q2VsbFZhbHVlKGVycm9yRGV0YWls
cyk7CgkJCXJvdy5jcmVhdGVDZWxsKDEzKS5zZXRDZWxsVmFsdWUoc2VjdXJpdGllc0NvbXBhbnkp
OwkJCQkJCgkJCXJvdy5jcmVhdGVDZWxsKDE0KS5zZXRDZWxsVmFsdWUoc2F2aW5nKTsKCQkJcm93
LmNyZWF0ZUNlbGwoMTUpLnNldENlbGxWYWx1ZShlYnMpOwoJCQlyb3cuY3JlYXRlQ2VsbCgxNiku
c2V0Q2VsbFZhbHVlKGNjKTsKCQkJcm93LmNyZWF0ZUNlbGwoMTcpLnNldENlbGxWYWx1ZShpY3Mp
OwoJCQlyb3cuY3JlYXRlQ2VsbCgxOCkuc2V0Q2VsbFZhbHVlKGlucHV0Rm9ybSk7CgkJCXJvdy5j
cmVhdGVDZWxsKDE5KS5zZXRDZWxsVmFsdWUobW9iaWxlT1RQKTsKCQkJcm93LmNyZWF0ZUNlbGwo
MjApLnNldENlbGxWYWx1ZShtb2JpbGVNUElOKTsKCQkJCgkJbGlzdEN1cnNvci5kZXN0cm95KCk7
Cgl9Cn0gCnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKc2hlZXQuYXV0b1NpemVDb2x1bW4oMCk7
ICAgIApzaGVldC5hdXRvU2l6ZUNvbHVtbigxKTsKc2hlZXQuYXV0b1NpemVDb2x1bW4oMik7CnNo
ZWV0LmF1dG9TaXplQ29sdW1uKDMpOwpzaGVldC5hdXRvU2l6ZUNvbHVtbig0KTsKc2hlZXQuYXV0
b1NpemVDb2x1bW4oNSk7CnNoZWV0LmF1dG9TaXplQ29sdW1uKDYpOwpzaGVldC5hdXRvU2l6ZUNv
bHVtbig3KTsKc2hlZXQuYXV0b1NpemVDb2x1bW4oOCk7CnNoZWV0LmF1dG9TaXplQ29sdW1uKDkp
OwpzaGVldC5hdXRvU2l6ZUNvbHVtbigxMCk7CnNoZWV0LmF1dG9TaXplQ29sdW1uKDExKTsKc2hl
ZXQuYXV0b1NpemVDb2x1bW4oMTIpOwpzaGVldC5hdXRvU2l6ZUNvbHVtbigxMyk7CnNoZWV0LmF1
dG9TaXplQ29sdW1uKDE0KTsKc2hlZXQuYXV0b1NpemVDb2x1bW4oMTUpOwpzaGVldC5hdXRvU2l6
ZUNvbHVtbigxNik7CnNoZWV0LmF1dG9TaXplQ29sdW1uKDE3KTsKc2hlZXQuYXV0b1NpemVDb2x1
bW4oMTgpOwpzaGVldC5hdXRvU2l6ZUNvbHVtbigxOSk7CQkKCkJ5dGVBcnJheU91dHB1dFN0cmVh
bSBib3MgPSBuZXcgQnl0ZUFycmF5T3V0cHV0U3RyZWFtKCk7CnRyeSB7CiAgICB0cnkgewoJCXdv
cmtib29rLndyaXRlKGJvcyk7CgkJYm9zLmNsb3NlKCk7Cgl9IGNhdGNoIChJT0V4Y2VwdGlvbiBl
KSB7CgkJLy8gVE9ETyBBdXRvLWdlbmVyYXRlZCBjYXRjaCBibG9jawoJCWUucHJpbnRTdGFja1Ry
YWNlKCk7Cgl9Cn0gZmluYWxseSB7CiAgICB0cnkgewoJCWJvcy5jbG9zZSgpOwoJfSBjYXRjaCAo
SU9FeGNlcHRpb24gZSkgewoJCS8vIFRPRE8gQXV0by1nZW5lcmF0ZWQgY2F0Y2ggYmxvY2sKCQll
LnByaW50U3RhY2tUcmFjZSgpOwoJfQp9Ci8vIHBpcGVsaW5lCklEYXRhQ3Vyc29yIHBpcGVsaW5l
Q3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKYnl0ZVtdIGJ5dGVBcnJheSA9IGJvcy50
b0J5dGVBcnJheSgpOwpJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvcl8xLCAiYnl0ZUFycmF5
IiwgYnl0ZUFycmF5ICk7CnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOwoJCgkKCQoJCgkKCQoJ
CgkKCQo=</value>
</Values>
